site_name: Guide demo

nav:
  - Home: index.md
  - Quick Start: quick_start.md
  - API References: api/index.md

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
              setup_commands:
                - import sys
                - sys.path.insert(0, "..")
    - bibtex:
        bib_file: "docs/refs.bib"
    - macros
    - mkdocs-jupyter:
      # include_source: True
      # execute: true
      # - allow_errors: false
    - callouts
    - glightbox
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
    - tags

theme:
    name: "material"
    logo: "https://assets.stickpng.com/images/5848152fcef1014c0b5e4967.png"
    palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    language: en
    features:
        - header.autohide
        - navigation.tabs
        - navigation.tracking
        - toc.follow
        - content.tooltips  # only sponsor

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "!!python/name:pymdownx.superfences.fence_code_format"
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "-"
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      auto_append:
        - abbreviations.md
